### ISSUE TITLE
Pre-build VI not being run

### ISSUE THREAD

**Issue by negentropicdev** [vipm-io/vipm-desktop-issues#10]
Trying to update a project to store a tag before the build runs but it doesn't appear to run. I added a dialog to the VI to verify and it never displays:
![image](https://user-images.githubusercontent.com/59840835/182751916-e0672787-6fa3-41c7-9fba-075378610078.png)

**Comment by jimkring** [comment]
@negentropicdev can you check to see if this is working in VIPM 2023.1 Beta?

**Comment by negentropicdev** [comment]
@jimkring Works! And I see a status display in the bottom about running it.

**Comment by jimkring** [comment]
@negentropicdev cool. I assume you're using Community Edition?

**Comment by negentropicdev** [comment]
2022Q3 Community, want me to try with others?

**Comment by negentropicdev** [comment]
Thank you!
