### ISSUE TITLE
VI Package Builder: Wrong version tooltip

### ISSUE THREAD

**Issue by thomas-allibe** [vipm-io/vipm-desktop-issues#11]
Not critical, just a little mistake.
The tooltips for "Minor" and "Fix/Bug" increment button is wrong :
![image](https://user-images.githubusercontent.com/66572526/183765447-30376da6-81e5-4946-ac5d-58717fca16c2.png)
![image](https://user-images.githubusercontent.com/66572526/183765501-a0f65f80-083f-4e0d-93c9-2f19eb073ffd.png)

Issue seen in VIPM 2021.1 (build 2754)

Thank you for your great work!

**Comment by jimkring** [comment]
Fixed in [VIPM 2023.1](https://docs.vipm.io/release-notes/2023.1/)
