### ISSUE TITLE
Subpalette name dialog stays open

### ISSUE THREAD

**Issue by OlivierJourdan** [vipm-io/vipm-desktop-issues#23]
When adding or renaming a subpalette, the dialog stays open when you click the OK button.

<img width="430" alt="image" src="https://user-images.githubusercontent.com/58081359/222413956-0eaf8551-b737-4273-bb78-bae6a8c0ccc6.png">

You can quit VIPM, and it asks for saving modification 😌
Then you get the window VI open

<img width="403" alt="image" src="https://user-images.githubusercontent.com/58081359/222414058-5d0e20e5-e3af-45ca-bed4-71b365c7c6db.png">

**Comment by jimkring** [comment]
Hi @OlivierJourdan. This should be fixed in 2023 Q3. You can get the release candidate here:

--> [VIPM 2023 Q3 for Windows Release Candidate Available](https://forums.vipm.io/topic/7493-vipm-2023-q3-for-windows-release-candidate-available/)
