### ISSUE TITLE
VIPM freezes when adding package repository

### ISSUE THREAD

**Issue by Flydroid** [vipm-io/vipm-desktop-issues#24]
**A Note to You (With Appreciation from Our Team)**

> Dear VIPM User,
> 
> Thank you for submitting this bug report! It makes a big difference to the VIPM Community and the VIPM Team. Please fill out as much or as little information below as makes sense to you -- we know your time is important and appreciate you sharing it with us. All of the information you provide (especially your VIPM Version, OS, and Steps to Reproduce) will greatly help us fix your bug.
>
> Note: Don't feel you need to delete any of the placeholder text.  The VIPM team will clean things up after you submit the issue.
> 
> Kind regards,
> 
> ~ The VIPM Community Team

**Short Description of the Bug (in one or two sentences)**
When I try to add a repository to VIPM in the repository manager the "VIPM - VI Package Repository" dialog doesnt close 
and the modal window is blocking the application. VIPM needs to be closed  from the windows task manager and when reopended the added repostitory is not there any more.

**Version Information**

VIPM Version and Build: 2023.1 (Build 2489)

Operating System Version:
Windows 10

LabVIEW Version:
LV2021 SP1

LabVIEW Bitness:
64-bit 

Virtualization or Processor Version Information
No!

**Steps To Reproduce**
1. Open VIPM
2. Go to Options
3. Got to Repository Manager
4.  Press "+" to add a repostiory and enter name. 
5. Both pressing "ok" or "cancel" freezes the application

**Expected behavior**
The repository gets added the the dialog disappears.

**Actual Behavior**
The dialog stays and cannot beclosed. Probably its a modal dialog. 

**Screenshots**
![image](https://user-images.githubusercontent.com/6762933/225894498-4776d164-6eb4-479c-b1d0-6efe416c8377.png)

**Anything else you'd like us to know?**
This is blocking the use of user repositories, a major feature of the pro version.

**Comment by jimkring** [comment]
Hi @negentropicdev. This should be fixed in 2023 Q3. You can get the release candidate here:

--> [VIPM 2023 Q3 for Windows Release Candidate Available](https://forums.vipm.io/topic/7493-vipm-2023-q3-for-windows-release-candidate-available/)
